Repository lancaster-university/codal-microbit-v2, pull requests merged in 2023-01, with the labels that each got.

#252 MicroBitRadio: fix setFrequencyBand() and do not reset tx power and frequency band in enable()
  inc/MicroBitRadio.h
  source/MicroBitRadio.cpp
Labels: bug

#246 docstrings: Minor fix in documented define name.
  inc/compat/MicroBitSerial.h
  source/compat/MicroBitSerial.cpp
Labels: documentation

#255 Simplify the BLE - Device Info - Model Number to only indicate V2.
  inc/bluetooth/MicroBitBLEManager.h
  model/MicroBit.cpp
  source/MicroBitPowerManager.cpp
  source/bluetooth/MicroBitBLEManager.cpp
Labels: bug, enhancement
